name: CFG_paths
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - cryptography=3.4.8
  - Flask=2.1.3
  - PyYAML=5.4.1  
  - werkzeug=2.2.1
  - networkx=2.8.5
  - graphviz
  - pydot
  - pip:
      # works for regular pip packages
      - graphviz
  